### ISSUE TITLE
AI Grenade Throw -  Due 10/7

### ISSUE THREAD

**Issue by Kami822** [Kami822/Cry-of-Athena#2]
**AI throws grenade, projectile movement based on equation that takes into account distance and height**
- [x] AI_Grenadier created and runs AI_Grenadier_BehaviorTree, initialized in AIGenesisDetourController
- [x] AI Behavior Tree has working BTT_ThrowGrenadeAttack
- [x] ThrowGrenadeAttack accounts for distance
- [x] ThrowGrenadeAttack accounts for height
- [x] Grenadier can throw grenade accurately towards their targets
- [x] Grenadier checks if has correct rotation before throw
- [x] Functionality merged with repository
- [x] Phillip's first task complete!

**Stretch goals:**
- [x] On hitting something, Grenade simulates physics (cancels projectile movement) and begins countdown to explosion
- [x] ThrowGrenadeAttack accounts for target's motion and throws based on predicted location

**Comment by engineereddeveloper03** [comment]
Finished the first pass of the algorithm today.  Got it to correctly throw a grenade at a stationary target.

Working on some unit tests to make sure it is working properly before carrying it over to the behavior tree.

**Comment by Kami822** [comment]
> Finished the first pass of the algorithm today. Got it to correctly throw a grenade at a stationary target.
> 
> Working on some unit tests to make sure it is working properly before carrying it over to the behavior tree.

Fantastic, that sounds like great progress. Thanks for the update, Phillip

**Comment by engineereddeveloper03** [comment]
Added grenade algorithm to behavior tree.  This is a rough pass and would need tweaking to feel right, but the expected functionality is there.

I also updated the branch with the latest from the master branch.  This is ready for a final test before bringing into the master branch.

**Comment by engineereddeveloper03** [comment]
Ensured unit is facing target before lobbing grenade.  Replaced SMGAttack with grenade attack so unit will still strafe during combat.

Cleaned up some BP logic.
